export const products = [
  {
    id: "phone-pixel-7a",
    name: "Pixel 7a",
    brand: "Google",
    category: "Phone",
    price: 449,
    originalPrice: 499,
    discount: 10,
    rating: 4.6,
    reviews: 2834,
    availability: "in_stock",
    stock: 58,
    popularity: 82,
    color: ["charcoal", "snow", "sea"],
    size: null,
    features: ["android", "camera", "5g", "wireless-charging", "ip67"],
    tags: ["android", "camera", "battery", "midrange"],
    addedDate: "2024-05-10",
    description: "A compact Android phone with strong camera quality and all-day battery life.",
  },
  {
    id: "phone-galaxy-a55",
    name: "Galaxy A55",
    brand: "Samsung",
    category: "Phone",
    price: 399,
    originalPrice: 449,
    discount: 11,
    rating: 4.4,
    reviews: 1956,
    availability: "in_stock",
    stock: 73,
    popularity: 75,
    color: ["awesome iceblue", "awesome lilac", "awesome navy"],
    size: null,
    features: ["android", "amoled", "5g", "water-resistant", "long-updates"],
    tags: ["android", "display", "battery", "budget"],
    addedDate: "2024-03-11",
    description: "A bright AMOLED phone with reliable performance and long software support.",
  },
  {
    id: "phone-iphone-15",
    name: "iPhone 15",
    brand: "Apple",
    category: "Phone",
    price: 799,
    originalPrice: 799,
    discount: 0,
    rating: 4.8,
    reviews: 8921,
    availability: "in_stock",
    stock: 120,
    popularity: 97,
    color: ["black", "blue", "green", "yellow", "pink"],
    size: null,
    features: ["ios", "a16-bionic", "usb-c", "dynamic-island", "ceramic-shield"],
    tags: ["ios", "camera", "premium", "performance"],
    addedDate: "2024-09-22",
    description: "A fast iOS phone with excellent video quality and a polished app ecosystem.",
  },
  {
    id: "phone-galaxy-s24",
    name: "Galaxy S24",
    brand: "Samsung",
    category: "Phone",
    price: 799,
    originalPrice: 799,
    discount: 0,
    rating: 4.7,
    reviews: 5412,
    availability: "in_stock",
    stock: 89,
    popularity: 93,
    color: ["onyx black", "marble gray", "cobalt violet", "amber yellow"],
    size: null,
    features: ["android", "snapdragon-8-gen-3", "ai-features", "120hz", "titanium-frame"],
    tags: ["android", "camera", "premium", "compact"],
    addedDate: "2024-01-17",
    description: "A premium Android phone with strong performance, a bright display, and polished cameras.",
  },
  {
    id: "phone-pixel-8-pro",
    name: "Pixel 8 Pro",
    brand: "Google",
    category: "Phone",
    price: 899,
    originalPrice: 999,
    discount: 10,
    rating: 4.7,
    reviews: 3789,
    availability: "in_stock",
    stock: 42,
    popularity: 88,
    color: ["obsidian", "porcelain", "bay"],
    size: null,
    features: ["android", "tensor-g3", "ai-features", "120hz", "thermometer"],
    tags: ["android", "camera", "premium", "ai-features"],
    addedDate: "2024-10-04",
    description: "A flagship Pixel with advanced camera tools, helpful AI features, and a large display.",
  },
  {
    id: "phone-oneplus-12r",
    name: "OnePlus 12R",
    brand: "OnePlus",
    category: "Phone",
    price: 499,
    originalPrice: 499,
    discount: 0,
    rating: 4.5,
    reviews: 1247,
    availability: "in_stock",
    stock: 65,
    popularity: 71,
    color: ["iron gray", "cool blue"],
    size: null,
    features: ["android", "snapdragon-8-gen-2", "100w-charging", "120hz", "5500mah"],
    tags: ["android", "performance", "fast-charging", "battery"],
    addedDate: "2024-02-06",
    description: "A value flagship Android phone with fast charging and smooth performance.",
  },
  {
    id: "phone-moto-g-power",
    name: "Moto G Power 5G",
    brand: "Motorola",
    category: "Phone",
    price: 249,
    originalPrice: 299,
    discount: 17,
    rating: 4.1,
    reviews: 987,
    availability: "in_stock",
    stock: 110,
    popularity: 60,
    color: ["mineral black", "pearl white"],
    size: null,
    features: ["android", "5g", "5000mah", "microsd", "splash-resistant"],
    tags: ["android", "budget", "battery", "large-display"],
    addedDate: "2024-06-18",
    description: "An affordable phone built around long battery life and a roomy screen.",
  },
  {
    id: "laptop-acer-swift-go",
    name: "Acer Swift Go 14",
    brand: "Acer",
    category: "Laptop",
    price: 749,
    originalPrice: 849,
    discount: 12,
    rating: 4.3,
    reviews: 1102,
    availability: "in_stock",
    stock: 34,
    popularity: 65,
    color: ["silver"],
    size: "14\"",
    features: ["windows", "oled", "intel-core-ultra", "16gb-ram", "512gb-ssd"],
    tags: ["student", "portable", "windows", "oled"],
    addedDate: "2024-04-22",
    description: "A slim Windows laptop for students and office work with a sharp OLED display.",
  },
  {
    id: "laptop-macbook-air-m2",
    name: "MacBook Air M2",
    brand: "Apple",
    category: "Laptop",
    price: 999,
    originalPrice: 1099,
    discount: 9,
    rating: 4.8,
    reviews: 7621,
    availability: "in_stock",
    stock: 95,
    popularity: 96,
    color: ["midnight", "starlight", "silver", "space gray"],
    size: "13.6\"",
    features: ["macos", "m2-chip", "magsafe", "fanless", "18hr-battery"],
    tags: ["macos", "battery", "portable", "premium"],
    addedDate: "2024-06-06",
    description: "A quiet, lightweight laptop with excellent battery life and smooth performance.",
  },
  {
    id: "laptop-lenovo-ideapad-flex",
    name: "Lenovo IdeaPad Flex 5",
    brand: "Lenovo",
    category: "Laptop",
    price: 629,
    originalPrice: 699,
    discount: 10,
    rating: 4.2,
    reviews: 834,
    availability: "in_stock",
    stock: 47,
    popularity: 58,
    color: ["storm grey", "abyss blue"],
    size: "14\"",
    features: ["windows", "touchscreen", "360-hinge", "ryzen-5", "8gb-ram"],
    tags: ["student", "touchscreen", "windows", "convertible"],
    addedDate: "2024-03-15",
    description: "A flexible 2-in-1 laptop for school, browsing, notes, and light creative work.",
  },
  {
    id: "laptop-asus-tuf-a15",
    name: "ASUS TUF Gaming A15",
    brand: "ASUS",
    category: "Laptop",
    price: 1099,
    originalPrice: 1299,
    discount: 15,
    rating: 4.5,
    reviews: 2945,
    availability: "in_stock",
    stock: 28,
    popularity: 80,
    color: ["mecha gray"],
    size: "15.6\"",
    features: ["windows", "rtx-4060", "ryzen-7", "144hz", "mil-std-810h"],
    tags: ["gaming", "windows", "performance", "dedicated-gpu"],
    addedDate: "2024-08-10",
    description: "A durable gaming laptop with strong graphics performance and a high-refresh display.",
  },
  {
    id: "headphones-sony-ch720n",
    name: "Sony WH-CH720N",
    brand: "Sony",
    category: "Headphones",
    price: 149,
    originalPrice: 149,
    discount: 0,
    rating: 4.5,
    reviews: 3210,
    availability: "in_stock",
    stock: 150,
    popularity: 78,
    color: ["black", "white", "blue"],
    size: null,
    features: ["noise-canceling", "bluetooth-5.2", "35hr-battery", "lightweight", "multipoint"],
    tags: ["noise-canceling", "wireless", "travel", "value"],
    addedDate: "2024-02-14",
    description: "Comfortable wireless headphones with active noise cancellation at a fair price.",
  },
  {
    id: "earbuds-airpods-pro-2",
    name: "AirPods Pro 2",
    brand: "Apple",
    category: "Earbuds",
    price: 249,
    originalPrice: 249,
    discount: 0,
    rating: 4.7,
    reviews: 12450,
    availability: "in_stock",
    stock: 200,
    popularity: 95,
    color: ["white"],
    size: null,
    features: ["noise-canceling", "spatial-audio", "usb-c", "adaptive-transparency", "ip54"],
    tags: ["ios", "noise-canceling", "wireless", "travel"],
    addedDate: "2024-09-09",
    description: "Premium earbuds with strong noise cancellation and seamless Apple device pairing.",
  },
  {
    id: "headphones-soundcore-q30",
    name: "Soundcore Life Q30",
    brand: "Soundcore",
    category: "Headphones",
    price: 79,
    originalPrice: 99,
    discount: 20,
    rating: 4.4,
    reviews: 5678,
    availability: "in_stock",
    stock: 180,
    popularity: 83,
    color: ["black", "blue", "pink"],
    size: null,
    features: ["noise-canceling", "bluetooth-5.0", "40hr-battery", "hi-res-audio", "foldable"],
    tags: ["budget", "noise-canceling", "battery", "wireless"],
    addedDate: "2023-11-20",
    description: "Budget wireless headphones with long battery life and adjustable noise cancellation.",
  },
  {
    id: "tablet-ipad-10",
    name: "iPad 10th Gen",
    brand: "Apple",
    category: "Tablet",
    price: 349,
    originalPrice: 449,
    discount: 22,
    rating: 4.6,
    reviews: 4521,
    availability: "in_stock",
    stock: 88,
    popularity: 89,
    color: ["blue", "pink", "yellow", "silver"],
    size: "10.9\"",
    features: ["ipados", "a14-bionic", "usb-c", "apple-pencil", "landscape-camera"],
    tags: ["tablet", "student", "creative", "ios"],
    addedDate: "2024-03-01",
    description: "A versatile tablet for notes, streaming, drawing, and everyday productivity.",
  },
  {
    id: "tablet-galaxy-tab-s9-fe",
    name: "Galaxy Tab S9 FE",
    brand: "Samsung",
    category: "Tablet",
    price: 449,
    originalPrice: 449,
    discount: 0,
    rating: 4.4,
    reviews: 1890,
    availability: "out_of_stock",
    stock: 0,
    popularity: 70,
    color: ["gray", "lavender", "mint", "silver"],
    size: "10.9\"",
    features: ["android", "s-pen-included", "ip68", "exynos-1380", "dex-mode"],
    tags: ["android", "student", "stylus", "water-resistant"],
    addedDate: "2024-04-05",
    description: "An Android tablet with included pen support for notes, sketching, and media.",
  },
  {
    id: "tablet-fire-hd-10",
    name: "Fire HD 10",
    brand: "Amazon",
    category: "Tablet",
    price: 139,
    originalPrice: 149,
    discount: 7,
    rating: 4.1,
    reviews: 6732,
    availability: "in_stock",
    stock: 210,
    popularity: 72,
    color: ["black", "denim", "lilac"],
    size: "10.1\"",
    features: ["fire-os", "octa-core", "3gb-ram", "microsd", "alexa"],
    tags: ["budget", "streaming", "reading", "family"],
    addedDate: "2023-10-18",
    description: "A low-cost tablet for streaming, reading, browsing, and casual household use.",
  },
  {
    id: "watch-garmin-vivoactive",
    name: "Garmin Vivoactive 5",
    brand: "Garmin",
    category: "Smartwatch",
    price: 249,
    originalPrice: 299,
    discount: 17,
    rating: 4.4,
    reviews: 1587,
    availability: "in_stock",
    stock: 55,
    popularity: 68,
    color: ["black", "white", "navy"],
    size: null,
    features: ["gps", "heart-rate", "sleep-tracking", "body-battery", "11-day-battery"],
    tags: ["fitness", "battery", "health", "gps"],
    addedDate: "2024-07-22",
    description: "A fitness-focused smartwatch with health tracking and strong battery life.",
  },
  {
    id: "watch-apple-se",
    name: "Apple Watch SE",
    brand: "Apple",
    category: "Smartwatch",
    price: 249,
    originalPrice: 279,
    discount: 11,
    rating: 4.6,
    reviews: 4310,
    availability: "in_stock",
    stock: 77,
    popularity: 86,
    color: ["midnight", "starlight", "silver"],
    size: null,
    features: ["watchos", "crash-detection", "heart-rate", "swim-proof", "family-setup"],
    tags: ["ios", "fitness", "health", "value"],
    addedDate: "2024-09-20",
    description: "A well-rounded Apple smartwatch for fitness tracking, notifications, and safety features.",
  },
  {
    id: "monitor-dell-s2722qc",
    name: "Dell S2722QC 27-inch 4K",
    brand: "Dell",
    category: "Monitor",
    price: 329,
    originalPrice: 399,
    discount: 18,
    rating: 4.5,
    reviews: 2154,
    availability: "in_stock",
    stock: 40,
    popularity: 74,
    color: ["silver"],
    size: "27\"",
    features: ["4k-uhd", "usb-c-65w", "hdr", "ips", "built-in-speakers"],
    tags: ["4k", "usb-c", "productivity", "home-office"],
    addedDate: "2024-01-30",
    description: "A sharp 4K USB-C monitor that works well for productivity and home office setups.",
  },
  {
    id: "monitor-lg-ultragear-27",
    name: "LG UltraGear 27-inch",
    brand: "LG",
    category: "Monitor",
    price: 299,
    originalPrice: 349,
    discount: 14,
    rating: 4.6,
    reviews: 3876,
    availability: "in_stock",
    stock: 62,
    popularity: 81,
    color: ["black"],
    size: "27\"",
    features: ["qhd", "165hz", "1ms-response", "nvidia-gsync", "hdr10"],
    tags: ["gaming", "high-refresh", "qhd", "low-latency"],
    addedDate: "2024-05-14",
    description: "A responsive QHD gaming monitor with a high refresh rate for smooth gameplay.",
  },
  {
    id: "keyboard-logitech-mx-keys",
    name: "Logitech MX Keys S",
    brand: "Logitech",
    category: "Keyboard",
    price: 109,
    originalPrice: 109,
    discount: 0,
    rating: 4.7,
    reviews: 4102,
    availability: "in_stock",
    stock: 95,
    popularity: 85,
    color: ["black", "pale gray"],
    size: null,
    features: ["wireless", "backlit", "multi-device", "smart-actions", "usb-c-charging"],
    tags: ["productivity", "wireless", "quiet", "backlit"],
    addedDate: "2024-06-12",
    description: "A quiet wireless keyboard with comfortable keys and multi-device switching.",
  },
  {
    id: "mouse-logitech-mx-master",
    name: "Logitech MX Master 3S",
    brand: "Logitech",
    category: "Mouse",
    price: 99,
    originalPrice: 99,
    discount: 0,
    rating: 4.8,
    reviews: 6543,
    availability: "in_stock",
    stock: 130,
    popularity: 91,
    color: ["graphite", "pale gray"],
    size: null,
    features: ["wireless", "ergonomic", "8000-dpi", "quiet-clicks", "usb-c"],
    tags: ["productivity", "wireless", "ergonomic", "quiet"],
    addedDate: "2024-04-08",
    description: "An ergonomic wireless mouse with precise scrolling and productivity shortcuts.",
  },
  {
    id: "speaker-jbl-flip-6",
    name: "JBL Flip 6",
    brand: "JBL",
    category: "Speaker",
    price: 129,
    originalPrice: 129,
    discount: 0,
    rating: 4.6,
    reviews: 7891,
    availability: "in_stock",
    stock: 145,
    popularity: 88,
    color: ["black", "blue", "red", "teal", "pink"],
    size: null,
    features: ["bluetooth-5.1", "ip67", "12hr-battery", "partyboost", "usb-c"],
    tags: ["portable", "waterproof", "bluetooth", "travel"],
    addedDate: "2024-01-05",
    description: "A rugged portable Bluetooth speaker with punchy sound and waterproof protection.",
  },
  {
    id: "camera-canon-r50",
    name: "Canon EOS R50",
    brand: "Canon",
    category: "Camera",
    price: 679,
    originalPrice: 679,
    discount: 0,
    rating: 4.5,
    reviews: 1654,
    availability: "out_of_stock",
    stock: 0,
    popularity: 62,
    color: ["black", "white"],
    size: null,
    features: ["mirrorless", "24mp", "4k-video", "eye-af", "wifi-bluetooth"],
    tags: ["creator", "mirrorless", "video", "beginner"],
    addedDate: "2024-02-28",
    description: "A beginner-friendly mirrorless camera for photos, video, and content creation.",
  },
  {
    id: "console-nintendo-switch-oled",
    name: "Nintendo Switch OLED",
    brand: "Nintendo",
    category: "Gaming",
    price: 349,
    originalPrice: 349,
    discount: 0,
    rating: 4.7,
    reviews: 9876,
    availability: "in_stock",
    stock: 75,
    popularity: 92,
    color: ["white", "neon red/blue"],
    size: null,
    features: ["oled-screen", "tabletop-mode", "64gb-storage", "lan-port", "wide-kickstand"],
    tags: ["gaming", "portable", "family", "oled"],
    addedDate: "2024-07-01",
    description: "A hybrid game console with a vivid OLED screen for handheld and TV play.",
  },
  {
    id: "router-eero-6-plus",
    name: "Eero 6 Plus",
    brand: "Eero",
    category: "Networking",
    price: 139,
    originalPrice: 159,
    discount: 13,
    rating: 4.4,
    reviews: 2310,
    availability: "out_of_stock",
    stock: 0,
    popularity: 64,
    color: ["white"],
    size: null,
    features: ["wifi-6", "mesh", "1gbps", "easy-setup", "alexa-built-in"],
    tags: ["wifi", "mesh", "home-office", "easy-setup"],
    addedDate: "2023-12-10",
    description: "A simple mesh Wi-Fi router for better coverage across apartments and homes.",
  },
  {
    id: "charger-anker-735",
    name: "Anker 735 Charger",
    brand: "Anker",
    category: "Accessory",
    price: 59,
    originalPrice: 65,
    discount: 9,
    rating: 4.6,
    reviews: 3456,
    availability: "in_stock",
    stock: 220,
    popularity: 77,
    color: ["black", "white"],
    size: null,
    features: ["65w", "usb-c", "gan-ii", "3-port", "foldable-plug"],
    tags: ["portable", "usb-c", "fast-charging", "travel"],
    addedDate: "2024-05-30",
    description: "A compact multi-port USB-C charger for phones, tablets, and lightweight laptops.",
  },
];
